### PR TITLE
(WIP) Split the settings into UI classes and logic classes.

### PR DESCRIPTION
**Pull request by loathingKernel**
As we discussed on Discord, this is my first pull request of the UI redesign. This pull request has to do with the Settings tab mostly.

Most of the design was done using Qt Designer, the relevant `.ui` files reside under  the `resources/ui/` folder mirroring their location in rare.
The these files were converted to python using `pyuic5` and put alongside their existing counterparts. For example, the UI class for the about tab
was put in the same folder as `about.py` and was named `about_ui.py`.

Since many lines were changed due to components being reused, the more important are listed below per file. Static strings were moved to the UI files for
translation purposes and some messages have been re-worded.

`extra_widgets.py`: PathEdit now contains the save button and the dialog can also filter by name, all forms using it have been updated
`rare.py`: Updated the look and fixed a bug where the Image Directory wouldn't change if `img_dir` wasn't specified in the settings file
`legendary.py`: Update the look, changed the Max Workers option into a SpinBox
`linux.py`: Update the look, changed Wine Executable option in to a PathEdit that filters for `wine` and `wine64`.
`game_settings.py`: Updated to reflect the changes in `linux.py` settings widget.  Added the system `compatibilitytools.d` to be search for potential proton versions

`dxvk.py`: Not done yet, needs some more love

Some screenshots:
Screenshot_2021-04-27_19-17-24
Screenshot_2021-04-27_19-17-36
Screenshot_2021-04-27_19-17-47

### CODE REVIEW

**Comment by Dummerle** [comment]
That looks awesome

**Comment by loathingKernel** [comment]
Thanks. Glad you like it. The global settings are pretty much done now that DXVK is done, onwards to thorough testing. I would like to continue with the per game settings, but the way it works right now is giving me a hard time, I will probably need to break them down to components instantiated just in time that get deleted after use instead of updating the same widgets.

Here is another screenshot:
Screenshot_2021-04-29_00-40-53

**Comment by Dummerle** [comment]
I tested it and it looks nice, but Discord rpc does not work and it does not detect my proton versions. I have my proton versions in ~/.steam/steam/steamapps/common. There are Proton 5.0 and Proton 5.13. 
And a suggeston: If you deselect all dxvk options, you can set the Combobox to Hidden.

**Comment by loathingKernel** [comment]
Can you check again? Proton should be fixed now, and DXVK should be set to hidden when all options are deselected. Also  I rebased everything. I saw a few commits about RPC recently, but I cannot see anything wrong with the code I modified. Can you test that again and let me know if it was an issue that was introduced here?

**Comment by loathingKernel** [comment]
I decided to merge the game settings I had been working on. There are a few pre-existing and a few new bugs to iron out, but here is what they look like so far.
Screenshot_2021-05-02_01-23-27
Screenshot_2021-05-02_01-23-50

**Comment by Dummerle** [comment]
Proton works now

**Comment by Dummerle** [comment]
Is it ready to merge?

**Comment by loathingKernel** [comment]
It needs to be rebased on the latest commits of dev, but then I think it can be merged.

**Comment by Dummerle** [comment]
I think it should be rebased on main. When the new release creates, I will merge it

**Comment by loathingKernel** [comment]
I didn't see the reply soon enough and I rebased on `dev` which might be for the best. A lot of translated text will be broken due to rewording a lot of the messages and they will need to be updated. As such it needs more work and `dev` is probably the best place to do it. To that effect I also added a label for protondb grade to match the rest of the UI.

As far as this PR is concerned all static translatable text is part of the UI, I removed any text that might need translation from the logic by using separate widgets for the static and the dynamic text.

A few words about the process I followed, this is also my suggested way of working for following changes after this PR and the structure I would like to follow in future PRs. The UI lives under `rare/ui` and mirrors the path of the class implementing the functionality, for example the UI of the following class
```
./rare/components/tabs/settings/about.py
```
lives under 
```
./rare/ui/components/tabs/settings/about.ui
```
After creating or adding new widgets in the ui file, the corresponding python file implementing it was generated by running `pyuic5 about.ui -x -o about.py`, and the resulting file was placed alongside the ui file (the `-x` switch adds a bit of extra code to make the file runnable for preview purposes).
```
./rare/ui/components/tabs/settings/about.py
```
For the external widgets that were instantiated at creation, such as `dxvk` and `rpc`, they where placed in provisioned layouts created through the designer to control their placement relative to the rest of the UI.

Other than that I think this is ready to be merged, I am available for any clarifications needed.

**Comment by Dummerle** [comment]
It looks really good, but i found one small issue: 

2021-05-17-104538_791x142_scrot

Then i will merge it

**Comment by loathingKernel** [comment]
That seems to be a CSS issue, as it happens to me too with `RareStyle.qss` (although differently as it cuts other labels), and not without it. I will look into it later on today and report back.

As a tangential point, I have implemented a way to define color palettes instead of CSS to theme the UI. It is doesn't allow the same freedom as CSS but it uses the design of the existing style with different colors, effectively making it more consistent with less work. It needs a bit of more work add the ability to select themes etc but it is getting there.

Here is an example.
Screenshot_2021-05-17_12-58-40

**Comment by Dummerle** [comment]
The option to select style sheet is very nice. It would be nice, if dark was default. 

2021-05-18-104724_681x151_scrot
This happens, if width is too small. Maybe it is possible, to put it in the next line

**Comment by loathingKernel** [comment]
> It would be nice, if dark was default.

Ok, will make RareStyle the default.

>  This happens, if width is too small. Maybe it is possible, to put it in the next line

That certainly should not happen, they are supposed to not compress more than their contents. What window manager do you use and does it honour the size hints from Qt? I remember this happening with a few tiling ones. I cannot reproduce it locally with a recent version of AwesomeWM.

I could probably will just put the behavior pane below the interface pane or the opposite, whatever looks better. I do not want them to make them do text wrapping as it will make the widgets jump around.

**Comment by Dummerle** [comment]
I use i3. I opened window in tiling mode,  but when i opend it in floating mode, the width can't be reduced. It would be nice, to reduce window size.

**Comment by loathingKernel** [comment]
I think a good compromise would be to put the interface and behavior panes below each other, possibly converting the widget as well as other affected widgets to vertical scrollareas too (which I do not like as an idea as it can look awkward). Right now the minimum possible window size is `917 x 592` which should be good enough for any modern display.

**Comment by Dummerle** [comment]
That's a good compromise

**Comment by Dummerle** [comment]
Thank you! If you want to make another Pull Request, please focus on Dialogs, like login dialog and launch dialog

**Comment by loathingKernel** [comment]
I was about to push the requested changes. I will open a new PR for them in a few hours.

**Comment by Dummerle** [comment]
Sorry

**Pull request merged**
