### PR TITLE
revert to using pyinstaller for windows

### PR DESCRIPTION
**Pull request by ChemicalXandco**
Deploying python software on windoze is hard.

### CODE REVIEW

**Comment by Dummerle** [comment]
Pyinstaller has some errors too. I don't know what is better. Is there another option to deploy on windows?

**Comment by ChemicalXandco** [comment]
There is `py2exe` but I am unable to get it working. Maybe it is easier just to support `pip` because that is better anyway?

**Comment by Dummerle** [comment]
Not everyone has pip installed. Is there an option to write an installer with a compiled language? Or is it too much work? 
I found pyqtdeploy, maybe it works better

**Comment by Dummerle** [comment]
You can't install games with pyinstaller too: 

IMG

WHY ARGPARSE???

**Comment by F0lkl0re** [comment]
Briefcase should work better. It was updated recently too.

**Comment by ChemicalXandco** [comment]
I will get to the bottom of this error. I have already narrowed it down to the usage of `multiprocessing` in legendary but it is very strange that it only happens when it is ran from an .exe file...

**Pull request closed without merging**
