### PR TITLE
Re-implement LoginDialog.

### PR DESCRIPTION
**Pull request by loathingKernel**
Still kinda WIP, the browse button doesn't do anything and some things are not fully tested. If I missed something as I do not use Windows, tell me.

Screenshot_2021-05-28_21-37-11
Screenshot_2021-05-28_21-37-31
Screenshot_2021-05-28_21-37-48
Screenshot_2021-05-28_21-38-31

### CODE REVIEW

**Comment by Dummerle** [comment]
I tested it and it looks nice, but I found some issues:

- With rare qss file, I have no feedback, which button was clicked. 

2021-05-29-234633_501x312_scrot


2021-05-29-234700_501x311_scrot
Same with Browser login

2021-05-29-234919_498x311_scrot
Loading does not stop (I am logged in)

And when login finished: 

2021-05-29-235204_304x53_scrot

**Comment by loathingKernel** [comment]
These are CSS issues, I didn't test against it, thanks for pointing them out. Generally the StyleSheet lacks any disabled feedback. It might be worth it to look into it in a more generalized manner. I wanted to implement animations for the stacked widget switching but it seemed quite complicated and tangential until it was ready.

>  Loading does not stop (I am logged in)

I am not sure what you mean. Once the loading finished it should just moves to the login success page.

**Comment by Dummerle** [comment]
> I am not sure what you mean. Once the loading is finished it should just moves to the login success page.

I am logged in in Epic Games Store installed via Lutris and I try to import it from it, but loading does not stop

**Comment by loathingKernel** [comment]
I just re-tested the import and it works for me. Could you investigate some more?

**Comment by Dummerle** [comment]
I found the error: `'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`. It was a corrupt file and i fixed it.
Maybe you can add an error message like this: 
```
    def do_login(self):
        self.status_label.setText(self.tr("Loading..."))
        if os.name == "nt":
            pass
        else:
            self.core.egl.appdata_path = os.path.join(self.prefix_combo.currentText(), self.appdata_path)
        try:
            if self.core.auth_import():
                logger.info(f"Logged in as {self.core.lgd.userdata['displayName']}")
                self.success.emit()
            else:
                self.status_label.setText(self.tr("Login failed."))
                logger.warning("Failed to import existing session")
        except FileExistsError as e:
            logger.warning(e)
            self.status_label.setText(str(e))
```

**Comment by loathingKernel** [comment]
Yeah, I will add that, thanks for looking into it.

**Comment by Dummerle** [comment]
When do you think it will be ready to merge?

**Comment by loathingKernel** [comment]
I wanted to add the ability to import the EGL Programdata from a windows partition and enable sync at login, but that can be taken into a different PR later. I think I can have it cleaned up as it is by the weekend.

**Comment by Dummerle** [comment]
Is it ready?

**Comment by Dummerle** [comment]
I will merge this pr. If you have any changes, create another one

**Pull request merged**
