### PR TITLE
feat: add freebsd support

### PR DESCRIPTION
**Pull request by z-ffqq**
This PR will add full FreeBSD support to Rare
image
image

### CODE REVIEW

**Review by TeknosQuet — APPROVED** [review]
+1

**Comment by loathingKernel** [comment]
Thank you for your contribution!

A few general questions:

* Can we safely assume that `FreeBSD == Linux` in all possible use-cases in Rare?
* Have you checked if Legendary detects `FreeBSD` accordingly, if not, have you made a PR there or is it something that should be done?

One hing missing AFAICS is to include the required modifications in `setup.py`, `requirements.txt` and other relevant dist files completeness.

**Comment by z-ffqq** [comment]
Legendary already works in FreeBSD OOTB, and in most cases, yes you can assume that FreeBSD == Linux

And also, thank you! I'll work more on this PR

**Comment by z-ffqq** [comment]
Another small issue is that the pip packae `pyqt5` won't build on FreeBSD normally, so the use of the `py39-qt5` package will be required

**Comment by z-ffqq** [comment]
image
i think the PR is now ready, let me know if i've missed anything!

**Comment by loathingKernel** [comment]
Looks fine to me :+1:

**Comment by Dummerle** [comment]
Thank you!

**Pull request merged**
