### PR TITLE
Redesign Install/Update dialog

### PR DESCRIPTION
**Pull request by loathingKernel**
Screenshot_2021-05-21_02-52-59

### CODE REVIEW

**Comment by loathingKernel** [comment]
There are a few issues with threading to resolve still, but if you could test it, it would be awesome.

**Comment by Dummerle** [comment]
It looks nice. How do i test selective downloads?

**Comment by loathingKernel** [comment]
I did it with Fortnite

**Comment by Dummerle** [comment]
2021-05-21-175913_547x284_scrot

**Comment by loathingKernel** [comment]
Screenshot_2021-05-21_19-11-31

It should be looking like this, mostly you are missing the frame with the selective downloads. Which is rather weird. The error in the sizes is because either you are in the previous commit (also why the frame is missing) or it happens due to threading sometimes. Did you have any conflicts when you pulled the PR locally?

**Comment by Dummerle** [comment]
Now it works

**Comment by loathingKernel** [comment]
The last commit has the potential to break a few things but it was required to make things consistent and less prone to break. Needs to be tested thoroughly as it touches a lot of places.

I opened this for review to get some testings going.

**Comment by Dummerle** [comment]
I will review it tomorrow

**Comment by loathingKernel** [comment]
Feel free to test, but before you merge it, I want to investigate a few more things. Maybe we can run `prepare_download` only in the dialog thread and not block the main interface after install is clicked any further.

**Pull request merged**
