### PR TITLE
Few small changes to not pollute the downloads changeset

### PR DESCRIPTION
**Pull request by loathingKernel**

### CODE REVIEW

**Comment by Dummerle** [comment]
What does the status bar do?

**Comment by loathingKernel** [comment]
It's the small bar that many main windows have at the bottom from displaying status messages, progress bars and other info.

**Comment by Dummerle** [comment]
What do you want to put in it?

**Comment by loathingKernel** [comment]
Because it can be useful and it doesn't take much space, it also makes the main window look more like a main window.

Some potential uses could be showing status messages there instead of popups, adding progressbars for verifications when not visible, displaying info. I do not have an exact use yet.

**Comment by Dummerle** [comment]
Thanks!

**Pull request merged**
