### PR TITLE
added modules for getting a game's steam id and its protondb tier!

### PR DESCRIPTION
**Pull request by gnanini**
imported the modules on utils.py

### CODE REVIEW

**Comment by Dummerle** [comment]
Thank you, but I have a lot to do at the moment. I will test it and merge it in the next days.

It would be nice, if you move all functions in one file. Something like rare/utils/id.py

**Comment by gnanini** [comment]
ok, good idea! leave a test function for you to test it?

**Comment by Dummerle** [comment]
You can remove the Test function

**Comment by Dummerle** [comment]
I tested it and I found some games causing issues. Satisfactory is called on Steam Satisfactory and on Epic Satisfactory Early Access or Satisfactory Experimental. If a game not exist, the app crashes, A small search algorithm should fix it.

Please set location of json file to ~/.cache/rare/game_list.json. Is it possible to save only games from your library with app_name? And please make the pull request to  dev branch

**Comment by Dummerle** [comment]
I will merge, the Pull request, and i will make some changes.

**Comment by gnanini** [comment]
@Dummerle, do I need to change this code, or get to another feature?

sorry for disappearing, I got some stuff to do at home... broken washing machine... and took some days of my computer!

**Comment by Dummerle** [comment]
I merged it and I made some changes. I save grades in a soon file in ~/.cache/Rare in a better format and I added a small bad search algorithm. It works for most games, but it is slow

**Comment by Dummerle** [comment]
I found here a Stackoverflow page for a search algo. [https://stackoverflow.com/questions/17388213/find-the-similarity-metric-between-two-strings](https://stackoverflow.com/questions/17388213/find-the-similarity-metric-between-two-strings). If you want to improve the search alogrithm it should be interesting. If you have a better solution, feel free to use it. 

I fomatted it like this: `{"373a4372c20540aca7fdd880d27fa49a": {"id": 648350, "grade": "platinum"},...}`.

**Comment by gnanini** [comment]
Will take a look

Em qua, 12 de mai de 2021 18:07, Dummerle ***@***.***>
escreveu:

**Comment by gnanini** [comment]
ok I will do it... 

I believe updating the json on every update of a game doesn't make sense because its id will not change, besides checking on every start of the app may increase dramatically its loading time... 

we should do a list of the person's game and check for its games only, but still the list is huge!

**Comment by Dummerle** [comment]
i did it already. But you can check, if you can improve it. At the first launch of the app, i try to find all steam ids and get grade from the api. Find steam id takes very long. Check grade from protondb takes less time, so this can be done on every update or once a week or whatever.

**Comment by gnanini** [comment]
But we have to check steam ids once per month, idk. Because the game list is ever growing...  

I will check the code this weekend! I will keep in touch more often...

**Pull request merged**
