### PR TITLE
 Adds the Chocolatey package as a way to install Rare

### PR DESCRIPTION
**Pull request by Xav83**
Hi @rare_devs,

I have created this Pull Request because I have resolved this [request for a Chocolatey package](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1099) and now, we can install **rare** using [Chocolatey](https://community.chocolatey.org/packages/rare).

For now, only the latest version (`1.8.9`) is available on Chocolatey. When new versions will be released, they will, then, be added to the Chocolatey package for users to enjoy. :slightly_smiling_face:

### CODE REVIEW

**Comment by loathingKernel** [comment]
Hi, thank you for your efforts to package it for Chocolatey. Personally I am not very familiar with Chocolatey packages outside of trying to use it many years ago. Could you give us a few more information on how it works and what might be relevant to us to take care of on our side if issues arise? I see you are using the  prepackaged `.msi`, which itself packages a `cx_freeze` application.

Have you tested the upcoming `1.9.0` release? In the new release we have a secondary application accessible through arguments  passed to Rare's executable. Rare's uses that to launch games in a separate independent process. Will Rare be able to find its executable if installed through Chocolatey for this to work?

**Comment by Xav83** [comment]
Hi @loathingKernel,

In order to facilitate the maintenance of this Chocolatey package, I am using the [Chocolatey Automatic Package Updater Module](https://github.com/majkinetor/au). This module checks regularly if there are update for the packages I maintain, and update the package if there is a new version available.

The Chocolatey package actually downloads your `msi` installer and runs it silently, so if there are issues with the msi installer you are releasing, so if there are issues with the installer itself, it will probably impact more than only the Chocolatey package :smile: 

For the new version `1.9.0`, and the system you are describing with the secondary application, I haven't tested it. If you look at the [Version History section](https://community.chocolatey.org/packages/rare#versionhistory), you will see that the beta version are available (they have been automatically created because of the [Chocolatey Automatic Package Updater Module](https://github.com/majkinetor/au) which can be installed and tested if you want. For example, the latest beta can be installed with the following command:
```
choco install rare --pre 
```
If the secondary application is also installed with the `msi` installer, then, it should not be a problem :wink: 

If you want to avoid to have people coming at you for issue from the Chocolatey package (like a version not accessible using Chocolatey), I can modify this Pull Request to specify that I am the maintainer of the Chocolatey package :wink: 

I hope that I have answered you question, but if you need any more information or have any other question, feel free to ask me :slightly_smiling_face:

**Comment by loathingKernel** [comment]
Sorry for the late reply. Yes, this answers most of my questions, thank you for clarifying.

> The Chocolatey package actually downloads your msi installer and runs it silently, so if there are issues with the msi installer you are releasing,

If I understand correctly all it does is download the `msi` and run it, correct? If so, yes, it should absolutely work, and if it doesn't, it is most likely our fault.

> If you want to avoid to have people coming at you for issue from the Chocolatey package (like a version not accessible using Chocolatey), I can modify this Pull Request to specify that I am the maintainer of the Chocolatey package

I think that this is up to you, I think it is not an issue for us to redirect people to you, or ping you on relevant issues. Since none of us daily drives Windows as far as I know, it might be better to first take a look at the issue at hand and then notify you, since more likely than not it will be a Rare issue than a packaging one. But if you want to give people a shortcut, feel free by all means.

@Dummerle I think this can be merged, more distribution routes is always good.

**Comment by Xav83** [comment]
Hi @loathingKernel,

Yes, the behavior is exactly as you summarized it :wink:

I will see you then in future issues (hopefully everything will work alright, and you will never have to ping me :laughing:)

About your note on GitHub Action, for now, the [Chocolatey Automatic Package Updater Module](https://github.com/majkinetor/au) is a solution which works combined with Appveyor. I know that the Chocolatey team has talked about a solution based on Azure DevOps suite (cf. this article from [pauby](https://blog.pauby.com/post/chocolatey-repository-using-azure-devops-artifacts-feed/)), but I am not aware of any solution based on GitHub Action, at the moment.

**Pull request merged**
